# build stage
FROM node:lts-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM caddy:2.4.6-alpine

COPY --from=builder /app/dist /usr/share/caddy
COPY Caddyfile.dev /etc/caddy/Caddyfile

EXPOSE 80